services:
  - type: web
    name: webapp-tarapaca
    env: node
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node src/index.js
    rootDir: backend
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://romamarcoleta:Ud4v2mgx@tarapaka1.xcghcmw.mongodb.net/arquitectura_tarapaca?retryWrites=true&w=majority&appName=tarapaka1
