-- 🔧 COPIAR Y PEGAR TODO ESTO EN POSTGRESQL

ALTER TABLE cotizaciones ALTER COLUMN id DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN nombre_material DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN unidad DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN cantidad DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN precio_unitario DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN estado DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN detalles DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN observaciones DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN updated_at DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN projects_id DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN insumos_id DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN providers_id DROP NOT NULL;
ALTER TABLE cotizaciones ALTER COLUMN users_id DROP NOT NULL;

-- ✅ LISTO
